spring:
  application:
    name: user-service-spring
  datasource:
    url: jdbc:postgresql://localhost:5432/users_database
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
